/**
 * Core type definitions for the Recipe Planner application.
 */

/**
 * An item in the user's pantry inventory.
 */
export interface PantryItem {
  id: string;
  name: string;
  amount: string;
}

/**
 * The place a kitchen stands in, used to look up a weather forecast.
 * Geocoded once when the user picks a town, then stored as coordinates so
 * no further name lookup is needed.
 */
export interface KitchenLocation {
  /** Display name as shown in the UI. Never sent to the LLM. */
  name: string;
  latitude: number;
  longitude: number;
}

/**
 * A kitchen profile bundling a set of staples (spice rack) and appliances,
 * e.g. "Home" vs. "Holiday home". The ACTIVE kitchen's lists live in the
 * legacy SPICE_RACK / KITCHEN_APPLIANCES storage keys; the `spices` and
 * `appliances` fields here are snapshots refreshed whenever the user
 * switches away from a kitchen, so the entry for the active kitchen may be
 * stale and must not be read while that kitchen is active.
 */
export interface Kitchen {
  id: string;
  name: string;
  spices: string[];
  appliances: string[];
  /**
   * Optional: absent for kitchens created before this field existed and for
   * everyone who never set a location. Unlike the list snapshots above, this
   * is authoritative even while the kitchen is active.
   */
  location?: KitchenLocation;
}

/**
 * An ingredient used in a recipe or shopping list.
 *
 * `amount` carries the unit with it ("500 g", "1 bunch", "a pinch"), which is
 * what the prompt has always asked for and what every display, the shopping
 * list's item key and the pantry matching read. The space between number and
 * unit belongs to that format, and the prompt now states it rather than only
 * showing it: its own examples wrote "500g" against this line's "500 g", and
 * the model went with the examples. There is deliberately no separate `unit`
 * field: nothing in the app computes with amounts, so splitting them would
 * only fork one concept across two fields.
 */
export interface Ingredient {
  item: string;
  amount: string;
}

/**
 * Estimated nutritional information per serving.
 * Values are rough estimates from the LLM.
 */
export interface Nutrition {
  calories: number;
  carbs: number;    // grams
  fat: number;      // grams
  protein: number;  // grams
}

/**
 * A generated recipe with ingredients and instructions.
 */
export interface Recipe {
  id: string;
  title: string;
  /**
   * How many people the recipe is written for. Optional: recipes stored or
   * shared before this field existed carry no count, and the card simply omits
   * it for them. Usually the app-wide people setting, but a style/wish may ask
   * for a single recipe to feed a different number, which is why the model
   * reports it rather than the client stamping it on.
   */
  servings?: number;
  // The method comes before the list because the list is ordered by first use
  // in it: see the key-order note on RecipeSchema in services/llm.ts.
  instructions: string[];
  ingredients: Ingredient[];
  usedIngredients: string[]; // List of PantryItem IDs used
  missingIngredients?: Ingredient[]; // Optional: excluded in shared recipes
  // Derived from the recipe above, and generated after it: see the key-order
  // note on RecipeSchema in services/llm.ts. Field order is meaningless to
  // TypeScript but not to the model, so the two are kept in step.
  time: string;
  nutrition?: Nutrition; // Optional for backwards compatibility
  comments?: string; // Optional fun fact or remark from the LLM
}

/**
 * A complete meal plan generated by the LLM.
 */
export interface MealPlan {
  recipes: Recipe[];
  shoppingList: Ingredient[];
}

/**
 * A notification displayed to the user (error or undo message).
 *
 * `anchor` controls where the toast renders. Omitted (or `'generate'`) keeps
 * it below the Generate button — the legacy spot. Other anchors render the
 * toast where the destructive action happened so it stays in viewport on
 * narrow screens. `anchorId` disambiguates among multiple instances of the
 * same anchor (currently only used for `'recipe'` to identify which card).
 */
export interface Notification {
  message: string;
  type: 'error' | 'undo';
  anchor?: 'generate' | 'shopping-list' | 'pantry' | 'recipe' | 'api-key';
  anchorId?: string;
  action?: {
    label: string;
    onClick: () => void;
    ariaLabel?: string; // Contextual aria-label for screen readers
  };
  timeout?: number; // Auto-dismiss after X milliseconds
}
