/**
 * Core type definitions for the Recipe Planner application.
 */

/**
 * An item in the user's pantry inventory.
 */
export interface PantryItem {
  id: string;
  name: string;
  amount: string;
}

/**
 * An ingredient used in a recipe or shopping list.
 */
export interface Ingredient {
  item: string;
  amount: string;
  unit?: string;
}

/**
 * Estimated nutritional information per serving.
 * Values are rough estimates from the LLM.
 */
export interface Nutrition {
  calories: number;
  carbs: number;    // grams
  fat: number;      // grams
  protein: number;  // grams
}

/**
 * A generated recipe with ingredients and instructions.
 */
export interface Recipe {
  id: string;
  title: string;
  time: string;
  ingredients: Ingredient[];
  instructions: string[];
  usedIngredients: string[]; // List of PantryItem IDs used
  missingIngredients: Ingredient[];
  nutrition?: Nutrition; // Optional for backwards compatibility
}

/**
 * A complete meal plan generated by the LLM.
 */
export interface MealPlan {
  recipes: Recipe[];
  shoppingList: Ingredient[];
}
